#!/usr/bin/env ruby

require 'builder'
require 'fileutils'
require 'yaml'
require 'json'

# --- CONFIG ---
OUTPUT_YAML = '_data/static_files.yml'
OUTPUT_HTML = '_includes/site-index.html'
PINS_FILE = '_data/pins.json'
INCLUDE_EXTENSIONS = ['.gif']

# Read pinned collections from pins.json (fall back to empty)
PINNED_DIRS = File.exist?(PINS_FILE) ? JSON.parse(File.read(PINS_FILE)) : []

# --- COLLECT FILES ---
def collect_files
  Dir.glob("*/*") # only include files in top-level folders
    .select { |f| File.file?(f) && INCLUDE_EXTENSIONS.include?(File.extname(f)) }
    .map do |f|
      {
        'path' => f,
        'modified_time' => File.mtime(f).to_i,
        'extname' => File.extname(f)
      }
    end
end

files = collect_files

# --- MARK IMPORTANT FILES ---
files.each do |file|
  top_dir = file['path'].split('/').first
  file['important'] = PINNED_DIRS.include?(top_dir)
end

# --- SORT FILES ---
files.sort_by! do |file|
  top_dir = file['path'].split('/').first
  importance = file['important'] ? PINNED_DIRS.index(top_dir) : PINNED_DIRS.length
  [importance, top_dir.downcase, file['path'].downcase]
end

# --- WRITE YAML ---
FileUtils.mkdir_p(File.dirname(OUTPUT_YAML))
File.write(OUTPUT_YAML, files.to_yaml)
puts "Wrote #{files.length} items to #{OUTPUT_YAML}"

# --- WRITE HTML ---
FileUtils.mkdir_p(File.dirname(OUTPUT_HTML))

File.open(OUTPUT_HTML, 'w') do |f|
  f.puts "<ul>"

  grouped = files.group_by { |item| item['path'].split('/').first }
  ordered_folders = PINNED_DIRS + (grouped.keys - PINNED_DIRS).sort

  ordered_folders.each do |folder|
    next unless grouped[folder]
    f.puts "  <li>#{folder}"
    f.puts "    <ul>"
    grouped[folder].each do |item|
      path = item['path']
      filename = File.basename(path)
      f.puts "      <li><a href=\"#{path}\" title=\"#{path}\" class=\"gif\">#{filename}</a></li>"
    end
    f.puts "    </ul>"
    f.puts "  </li>"
  end

  f.puts "</ul>"
end

puts "Wrote HTML index to #{OUTPUT_HTML}"
