#!/usr/bin/env ruby

require 'builder'
require 'fileutils'
require 'yaml'

# --- CONFIG ---

output_yaml = '_data/static_files.yml'
output_html = '_includes/site-index.html'

important_dirs = [
  'goldblum',
  'fail',
  'all the favs'
]

# Include only visible top-level folders, excluding script/ and anything starting with "_"
included_dirs = Dir.glob("*").select do |d|
  File.directory?(d) && !d.start_with?("_") && d != "script"
end

# --- BUILD INDEX ---

items = []

included_dirs.each do |dir|
  Dir.glob("#{dir}/**/*").each do |path|
    next unless File.file?(path)

    extname = File.extname(path)
    modified_time = File.mtime(path).to_i

    item = {
      'path' => path,
      'modified_time' => modified_time,
      'extname' => extname
    }

    important_index = important_dirs.find_index { |important| path.start_with?("#{important}/") }
    item['important_index'] = important_index if important_index

    items << item
  end
end

# --- SORTING ---

items.sort_by! do |item|
  if item.key?('important_index')
    [0, item['important_index'], item['path']]
  else
    [1, item['path']]
  end
end

items.each { |item| item.delete('important_index') }

# --- WRITE YAML ---

FileUtils.mkdir_p(File.dirname(output_yaml))
File.open(output_yaml, 'w') { |f| f.write(items.to_yaml) }

puts "Wrote #{items.size} items to #{output_yaml}"

# --- WRITE HTML INDEX ---

FileUtils.mkdir_p(File.dirname(output_html))
File.open(output_html, 'w') do |f|
  f.puts "<ul>"
  items.each do |item|
    f.puts "  <li><a href='/#{item['path']}'>#{item['path']}</a></li>"
  end
  f.puts "</ul>"
end

puts "Wrote site index to #{output_html}"
