#!/usr/bin/env ruby

require 'builder'
require 'fileutils'
require 'yaml'

# --- CONFIG ---
OUTPUT_YAML = '_data/static_files.yml'
OUTPUT_HTML = '_includes/site-index.html'
INCLUDE_EXTENSIONS = ['.gif']
IMPORTANT_DIRS = %w[icons pixelated homages] # in desired order

# --- COLLECT FILES ---

def collect_files
  Dir.glob("**/*")
    .select { |f| File.file?(f) && INCLUDE_EXTENSIONS.include?(File.extname(f)) }
    .map do |f|
      {
        'path' => f,
        'modified_time' => File.mtime(f).to_i,
        'extname' => File.extname(f)
      }
    end
end

files = collect_files

# --- MARK IMPORTANT FILES ---
files.each do |file|
  top_dir = file['path'].split('/').first
  file['important'] = IMPORTANT_DIRS.include?(top_dir)
end

# --- SORT FILES ---
files.sort_by! do |file|
  importance = file['important'] ? IMPORTANT_DIRS.index(file['path'].split('/').first) : IMPORTANT_DIRS.length
  [importance, file['path']]
end

# --- WRITE YAML ---
FileUtils.mkdir_p(File.dirname(OUTPUT_YAML))
File.write(OUTPUT_YAML, files.to_yaml)
puts "Wrote #{files.length} items to #{OUTPUT_YAML}"

# --- WRITE HTML ---
FileUtils.mkdir_p(File.dirname(OUTPUT_HTML))

File.open(OUTPUT_HTML, 'w') do |f|
  f.puts "<ul>"

  grouped = files.group_by { |item| item['path'].split('/').first }

  grouped.each do |folder, folder_files|
    f.puts "  <li>#{folder}"
    f.puts "    <ul>"
    folder_files.each do |item|
      path = item['path']
      filename = File.basename(path)
      f.puts "      <li><a href=\"#{path}\" title=\"#{path}\" class=\"gif\">#{filename}</a></li>"
    end
    f.puts "    </ul>"
    f.puts "  </li>"
  end

  f.puts "</ul>"
end

puts "Wrote HTML index to #{OUTPUT_HTML}"
